config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
  	resources :top_restaurants, only: [:new, :create, :destroy]
  end

  root to: 'restaurants#index'

  get    '/signup', to: 'users#new'
  post   '/users', to: 'users#create'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :top_restaurants
	has_many :users, through: :top_restaurants
	
end

app/models/top_restaurant.rb
class TopRestaurant < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
  
	has_many :top_restaurants
	has_many :restaurants, through: :top_restaurants

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/top_restaurants_controller.rb
class TopRestaurantsController < ApplicationController
	
	def new
		@toprestaurant = TopRestaurant.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
	    @toprestaurant = TopRestaurant.create(user_id: params[:user_id], restaurant_id: params[:restaurant_id])
	    
	    # if request.xhr?
     #    	render partial: 'user', locals:{user: current_user}
     #    else
        	redirect_to root_path
        # end
	end

	def destroy
		@user = User.find(params[:user_id])
		@restaurant = Restaurant.find(params[:id])
		TopRestaurant.where(user_id: @user.id, restaurant_id: @restaurant.id).destroy_all
	    redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new 
		@user = User.new
	end

	def create
	    @user = User.new(user_params)
	    if @user.save
	      session[:user_id] = @user.id
	      redirect_to root_path

	    else
	      render 'new'
	    end
  	end

  	def show
  		@user = User.find(params[:id])
  		@toprestaurants = @user.top_restaurants
  	end

  	private
  	def user_params
    	params.require(:user).permit(:name, :email, :password)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def is_current_user?(user)
    current_user == user
  end
end

app/helpers/top_restaurant_helper.rb
module TopRestaurantHelper
end

app/helpers/top_restaurants_helper.rb
module TopRestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateNight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	  <ul>
		  	<li id="home"> <%= link_to 'Home', root_path %> </li>
				<% if current_user %>
				<li> <%= link_to 'Logout', logout_path, method: :delete %> </li>
				<li> <%= link_to current_user.name, current_user %></li>
				<% else %>
				<li id="signup">	<%= link_to 'Signup', signup_path %> </li>
				<li>	<%= link_to 'Login', login_path %> </li>
				<% end %>
		</ul>

    <%= yield %>

  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<img src="<%= restaurant.image_url %>" width="260" height="190"> <br>	
<a href="<%= restaurant.url %>"><%= restaurant.name %></a> <br>
<a href="tel:<%= restaurant.phone %>"><%= restaurant.phone %></a> <br>
<div class="ui label">
	Rating: <%= restaurant.rating %>
</div>
<div class="ui label">
	Price: <%= restaurant.price %>
</div> <br>
<% if !current_user %>
	<div class="ui lightgrey button">
		<%= button_to "Add to Top Restaurants", login_path %>
	</div>
<% else %>
	<% if current_user.restaurants.include?(restaurant) %>
		<div>
			<%= link_to content_tag(:i, '', :class => "fa fa-times"), user_top_restaurant_path(current_user, restaurant), method: :delete, remote: true, class: "ui small yellow button delete", id: "remove" %>
		<p id="remove-message">Removed</p>
		</div>
	<% else %>
		<div>
			<%= link_to content_tag(:i, '', :class => "fa fa-heart"), user_top_restaurants_path(current_user, :restaurant_id => restaurant.id), method: :post, remote: true, class: "ui small yellow button add", id: "heart" %>
			<p id="add-message">Added! </p> 
		</div>
	<% end %>
<% end %>

app/views/restaurants/index.html.erb
<h2 class="ui orange center aligned icon header" id="title">
  <i class="circular cocktail icon"></i>
  Date Night
</h2>


<div class="content">
	<% @restaurants.each do |restaurant| %>

		<div class="restaurant-item">
			<%= render "restaurant", collection: @restaurants, restaurant: restaurant %> 
		</div>

	<% end %>
</div>

app/views/top_restaurants/restaurant.js.erb
$('.fa-heart').on('click', function(){
	console.log('clicked')
})

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Name"%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

    <p>Already a user? <%= link_to "Sign in" %></p>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="header"> Top Restaurants</h1> <br><br>

<div class="content">

	<% current_user.restaurants.each do |restaurant| %>
			<div class="restaurant-item">
				<%= render "restaurants/restaurant", collection: @restaurants, restaurant: restaurant %> 
			</div>
	<% end %>

</div>